server {
    listen 80;

    server_name localhost;

    location /assets/ {

        alias /usr/share/nginx/assets/;


        add_header Cache-Control "public, max-age=300";


        add_header X-CDN-Simulation "nginx-local-static-assets";

        add_header X-Content-Type-Options "nosniff";


        try_files $uri =404;
    }
}